//background 与 popup 通信的type
export const GET_KEYRING_STATUS_ONLY = "get-keyring-status-only"
export const GET_KEYRING_STATUS = "get-keyring-status"
export const NEW_MNEMONIC_KEY = "new-mnemonic-key"
export const NEW_PRIVATE_KEY_KEY = "new-private-key-key"
export const LOCK_KEYRING = "lock-keyring"
export const UNLOCK_KEYRING = "unlock-keyring"
export const DELETE_KEYRING = "delete-keyring"
export const SELECT_KEYRING = "select-keyring"
export const SHOW_SENSITIVE_KEYRING_DATA = "show-sensitive-keyring-data"
