//background 与 popup 通信的type
export const RESTORE_KEYRING = "restore-keyring"
export const NEW_MNEMONIC_PASSWORD = "new-mnemonic-password"
export const NEW_MNEMONIC = "new-mnemonic"
export const IMPORT_MNEMONIC_PASSWORD = "import-mnemonic-password"
export const IMPORT_MNEMONIC = "import-mnemonic"
export const RECOVER_MNEMONIC = "recover-mnemonic"
export const UNLOCK_KEYRING = "unlock-keyring"
export const LOCK_KEYRING = "lock-keyring"
export const CHANGE_ACCOUNT = "change-account"
export const VIEW_MNEMONIC = "view-mnemonic"